# Rappels de Python pour le calcul scientifique

Préliminaires : importer les bibliothèques pertinentes, notamment NumPy.

In [170]:
import sys                       # Importation d'un module.
import numpy as np               # Importation avec un nom raccourci.
from numpy import array, newaxis # Importation ciblée de fonctions ou variables spécifiques.

## Manipulations de base d'objets simples

Python comporte des types de base : nombres, texte (chaînes de caractères), listes et apparentés. Le typage est automatique.

In [171]:
x = 1
y = 2
xy = x / y    # Nombre à virgule flottante bien que x et y soient entiers.
z = -1 + 0.5j # Nombre complexe.
type(x), type(y), type(xy), type(z)

(int, int, float, complex)

Les chaînes de caractères peuvent être notées avec les guillemets simples ou doubles. On peut les concaténer avec l'opérateur + ; mais il est généralement plus pratique d'utiliser la fonction de formatage d'autres objets à l'intérieur d'un texte.

In [172]:
s1 = 'Ceci est du texte.'
s2 = "Ceci aussi, et inclut l'apostrophe."
s3 = s1 + " " + s2 # Concaténation.
print(s3)
s4 = f'Ce texte indique "{s1}", ainsi que la valeur de {y=} ou même de {x + z ** 2=}.'
print(s4)

Ceci est du texte. Ceci aussi, et inclut l'apostrophe.
Ce texte indique "Ceci est du texte.", ainsi que la valeur de y=2 ou même de x + z ** 2=(1.75-1j).


Les listes et assimilées sont indexées par des crochets, en partant de l'indice 0 (depuis le début) ou -1 (depuis la fin). Leur contenu est libre (elles peuvent notamment contenir des objets de types différents). On les crée avec des crochets pour les listes, des parenthèses pour les tuples (comme des listes mais non modifiables).

In [173]:
liste1 = [1, 2, 42, 'toto']
print(f'{type(liste1)=}')       # list
print(f'{liste1[0]=}')          # 1
print(f'{liste1[-1]=}')         # 'toto'
liste1[2] = -1                  # Maintenant le 3e élément (à l'indice 2) vaut -1.
print(f'{liste1=}')             # [1, 2, -1, 'toto']

type(liste1)=<class 'list'>
liste1[0]=1
liste1[-1]='toto'
liste1=[1, 2, -1, 'toto']


On a aussi les tuples, plus efficaces mais qui ne peuvent pas être modifiés. On en a rencontré un implicitement ci-dessus quand on a affiché les 4 types séparés par des virgules. On les crée avec des parenthèses (optionnelles sauf ambigüité).

In [174]:
tuple1 = (4, 5, 7)
tuple1[1]                        # Interdit de le modifier !

5

L'indexation peut se faire sur plusieurs éléments à la fois («slicing») en spécifiant l'indice du premier élément qu'on souhaite extraire, celui avant lequel on s'arrête, et optionnellement le pas.

In [175]:
liste2 = ["", "a", "b", "c", "d", "e"]
print(liste2[1:4])   # 'a', 'b', 'c'
print(liste2[1:4:2]) # 'a', 'c'
print(liste2[:3])    # '', 'a', 'b'

['a', 'b', 'c']
['a', 'c']
['', 'a', 'b']


On notera que les chaînes de caractères aussi peuvent être indexées. Tous ces types sont appelés des *itérables*.

### Exercice
Extraire le contenu des accolades dans la chaîne : '{contenu}'.

Enfin, on peut définir des fonctions ou exécuter des boucles en indentant des blocs de code, c'est à dire en les faisant précéder d'espaces :

In [176]:
def moitie_de(x):
    y = x / 2
    return y

print(moitie_de(4)) # 2.

for k in (1, 2, 3):
    print(moitie_de(k))

print("\n") # Saut de ligne.
for k in range(4): # Fait office de (0 ... 3), car on s'arrête avant le dernier indice.
    print(moitie_de(k))

2.0
0.5
1.0
1.5


0.0
0.5
1.0
1.5


## Manipulation de tableaux

La plupart des opérations de calcul doivent se faire sur des valeurs multiples. NumPy fournit des objets tableaux pour le calcul vectoriel ou matriciel. Il est plus efficace de les utiliser que d'écrire les boucles explicitement. On les initialise avec des listes ou avec diverses fonctions.

In [177]:
array(range(10, 14)) # Rappelez-vous, on a importé array de numpy.

array([10, 11, 12, 13])

In [178]:
np.linspace(42, 43, 6) # Rappelez-vous, on a importé numpy sous le nom np.

array([42. , 42.2, 42.4, 42.6, 42.8, 43. ])

In [179]:
np.zeros((3, 6)) # Les dimensions sont données par un tuple.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [180]:
id4 = np.identity(4)
id4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---
Les tableaux sont indexables au même titre que d'autres itérables, mais ils supportent plusieurs axes.

In [181]:
id4[0,0], id4[0,2] # 1, 0

(1.0, 0.0)

In [182]:
id4[0:2, 1:] # Lignes 0 et 1, colonnes 1, 2, ...

array([[0., 0., 0.],
       [1., 0., 0.]])

On peut aussi masquer certains éléments en indexant par une expression booléenne (vraie/fausse).

In [183]:
r = np.random.normal(size = (20,)) # 20 échantillons de bruit gaussien.
print(r)
r[r > 1] = 1                       # On plafonne à 1.
print(r)

[-0.9854231   0.50557843  1.06020619 -0.5524703   0.79326538  0.97500221
  0.53913384 -0.92229957  2.38188957  0.46099527 -0.70109784  1.25782316
  0.39051079  0.78276894  0.14552068  0.52131882  0.88033247  2.54551459
  1.35488225  0.55615341]
[-0.9854231   0.50557843  1.         -0.5524703   0.79326538  0.97500221
  0.53913384 -0.92229957  1.          0.46099527 -0.70109784  1.
  0.39051079  0.78276894  0.14552068  0.52131882  0.88033247  1.
  1.          0.55615341]


### Exercice
Sans utiliser de boucles ```for / while ```:
créer une matrice $M \in \mathbb{R}^{5\times6}$ aléatoire à coefficients uniformes dans $[-1, 1]$, puis remplacer une colonne sur deux par sa valeur moins le double de la colonne suivante. Remplacer enfin les valeurs négatives par 0 en utilisant un masque.

L'indexation permet aussi de répliquer un tableau sur plusieurs dimensions avec la constante ```numpy.newaxis```. Les dimensions de longueur 1 se répliquent automatiquement pour être compatibles avec des tableaux plus grands. (Chercher les règles exactes dans la documentation de NumPy, concept de «broadcast».)

In [184]:
valeurs03 = array(range(4))
for a in (valeurs03,
          valeurs03[:, newaxis],
          valeurs03[newaxis, :],
          valeurs03[newaxis, :] + valeurs03[:, newaxis]):
    print(f'Dimensions : {a.shape}\nTableau :\n{a}\n')


Dimensions : (4,)
Tableau :
[0 1 2 3]

Dimensions : (4, 1)
Tableau :
[[0]
 [1]
 [2]
 [3]]

Dimensions : (1, 4)
Tableau :
[[0 1 2 3]]

Dimensions : (4, 4)
Tableau :
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]



Les opérations usuelles ```+```, ```*``` opèrent élément par élément, mais on dispose aussi du produit scalaire ou matriciel (selon les dimensions des tableaux) via la méthode ```dot()``` :

In [185]:
M = array([[1, 2], [3, 4]])
vecX10 = array([10, 0])
vecX10_ligne = vecX10[newaxis, :]
vecX10_colonne = vecX10[:, newaxis]
vecY20 = array([0, 20])
vecY20_ligne = vecY20[newaxis, :]
vecY20_colonne = vecY20[:, newaxis]

In [186]:
vecX10 * vecY20

array([0, 0])

In [187]:
vecX10.dot(vecY20)

0

In [188]:
vecX10_ligne.dot(vecY20_colonne)

array([[0]])

In [189]:
vecX10_colonne.dot(vecY20_ligne)

array([[  0, 200],
       [  0,   0]])

In [190]:
M.dot(vecX10)

array([10, 30])

In [191]:
M.dot(vecX10_colonne)

array([[10],
       [30]])

In [192]:
vecX10_ligne.dot(M)

array([[10, 20]])

Le début de l'exercice ci-dessus (prendre une matrice 5×6 et soustraire à une colonne sur deux le double de la colonne suivante) aurait pu être résolu par une multiplication de matrices au lieu d'une manipulation de colonnes :

In [193]:
r5x6 = np.random.uniform(-1, 1, size = (5,6))
print(r5x6, end = '\n\n')
mult = np.identity(6)
mult[1, 0] = mult[3, 2] = mult[5, 4] = -2
print(mult, end = '\n\n')
print(r5x6.dot(mult))

[[ 0.77666369  0.46359653 -0.6561527   0.75917823  0.27070037 -0.53697802]
 [ 0.25539254  0.03410407  0.2692803   0.71570493  0.60123048 -0.54935863]
 [ 0.55540833 -0.79821711 -0.61198005  0.00796589  0.41784282 -0.35642793]
 [-0.98544924 -0.30436689 -0.40493722 -0.37084496  0.02559035 -0.81216201]
 [ 0.64256007  0.81701142  0.88785749 -0.69619054  0.57301609  0.32099342]]

[[ 1.  0.  0.  0.  0.  0.]
 [-2.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -2.  1.]]

[[-0.15052937  0.46359653 -2.17450916  0.75917823  1.34465642 -0.53697802]
 [ 0.1871844   0.03410407 -1.16212957  0.71570493  1.69994774 -0.54935863]
 [ 2.15184255 -0.79821711 -0.62791182  0.00796589  1.13069868 -0.35642793]
 [-0.37671546 -0.30436689  0.33675269 -0.37084496  1.64991436 -0.81216201]
 [-0.99146277  0.81701142  2.28023858 -0.69619054 -0.06897075  0.32099342]]


Les valeurs d'un tableau peuvent être écrites ou sauvegardées dans un fichier (avec un commentaire éventuel en en-tête) via ```numpy.savetxt()``` (et relues par ```numpy.loadtxt()```. Ce sera utile pour sauvegarder des signaux échantillonnés et les faire traiter par un programme externe.

In [197]:
np.savetxt(sys.stdout,      # stdout est un fichier qui affiche à l'écran
           mult,            # Tableau à afficher
           delimiter = ";", # Séparateur de colonnes (optionnel)
           fmt = "%.1f",    # Formatage des nombres (optionnel)
           header = "Matrice qui soustrait le double d'une colonne sur deux")

# Matrice qui soustrait le double d'une colonne sur deux
1.0;0.0;0.0;0.0;0.0;0.0
-2.0;1.0;0.0;0.0;0.0;0.0
0.0;0.0;1.0;0.0;0.0;0.0
0.0;0.0;-2.0;1.0;0.0;0.0
0.0;0.0;0.0;0.0;1.0;0.0
0.0;0.0;0.0;0.0;-2.0;1.0
